
const ADD_QUERY              = 'ADD_QUERY';
const ADD_QUERY_NODE         = 'ADD_QUERY_NODE';
// todo ...
const REMOVE_QUERY_NODE      = 'REMOVE_QUERY_NODE';
// todo ...
const VALIDATE_QUERY_CONTENT = 'VALIDATE_QUERY_CONTENT';
const BUILD_QUERY_CONTENT    = 'BUILD_QUERY_CONTENT';
const SET_QUERY_FETCHING     = 'SET_QUERY_FETCHING';
const SET_QUERY_DATA 		 = 'SET_QUERY_DATA';

export {
	ADD_QUERY, 
	ADD_QUERY_NODE,
	REMOVE_QUERY_NODE,
	VALIDATE_QUERY_CONTENT,
	BUILD_QUERY_CONTENT,
	SET_QUERY_FETCHING,
	SET_QUERY_DATA
};